name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on:  ubuntu-latest # ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     include:
    #       - os: ubuntu-latest
    #       - os: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: apt install libsqlite3-dev libjsoncpp-dev
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare Files
      run: |
        cp ${{github.workspace}}/build/fsd ${{github.workspace}}/program_directory/unix/
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: fsd-linux
        path: ${{github.workspace}}/program_directory/unix/
        if-not-files-found: error
